desc "Simple task"
task :simple do
  puts "Hello World!"
end

desc "Namespaced task"
task "a:b:c:d:e:f:g:h:i:j:k:l:m:n:o:p:q:r:s:t:u:v:w:x:y:z" do
  # do nothing
end

desc "Task with arguments"
task :arguments

desc "Task with dependencies"
task :dependencies

directory "tmp/www"

desc "Generate tmp/www/index.html"
file "tmp/www/index.html" => "tmp/www" do |task|
  File.open(task.name, "w") do |file|
    file.puts("<html>Hello World!</html>")
  end
end

rule ".o" => [".c"] do |task|
  sh "gcc #{task.source} -c -o #{task.name}"
end
